name: Iceberg Integration Tests

on:
  push:
    branches:
      - "feat/testing_framework"
  pull_request:
    branches:
      - "feat/testing_framework*"

jobs:
  test:
    runs-on: alpine-3.18
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      # Use your local Docker environment instead of creating containers
      - name: Start MySQL and related services
        run: |
          pushd ./drivers/mysql
          docker compose up -d
          popd

      - name: Start Iceberg-related services
        run: |
          pushd ./writers/iceberg/local-test
          docker compose up -d
          popd
    
      # Wait for services to be ready
      - name: Wait for services to be ready
        run: sleep 30

      # Verify services are running
      - name: Verify MySQL is running
        run: |
          docker ps | grep mysql && echo "MySQL is running"

      - name: Verify Postgres is running
        run: |
          docker ps | grep postgres && echo "Postgres is running"

      - name: Verify MinIO is running
        run: |
          docker ps | grep minio && echo "MinIO is running"

      - name: Verify Spark Iceberg is running
        run: |
          docker ps | grep spark-iceberg && echo "Spark Iceberg is running"
       # Prepare Data Directories and Run Tests
      - name: Create data directories with proper permissions
        run: |
          sudo mkdir -p /home/runner/work/olake/olake/writers/iceberg/local-test/data/postgres-data
          sudo mkdir -p /home/runner/work/olake/olake/writers/iceberg/local-test/data/minio-data
          sudo mkdir -p /home/runner/work/olake/olake/writers/iceberg/local-test/data/ivy-cache
          sudo chmod -R 777 /home/runner/work/olake/olake/writers/iceberg/local-test/data
      
      # Install go dependencies and build
      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      # Skip the Maven build if it's already in your local setup
      # Or keep it if still needed
      - name: Run Maven build
        run: |
          cd ./writers/iceberg/debezium-server-iceberg-sink
          mvn clean package -DskipTests

      # Run the integration tests
      - name: Run integration tests
        run: go test -v ./drivers/mysql/internal/... -tags=integration --timeout 0

      # Clean up containers when done
      - name: Clean up Docker containers
        run: |
          pushd ./writers/iceberg/local-test
          docker compose down
          popd
          
          pushd ./drivers/mysql
          docker compose down
          popd